name: flutter_llama_example
description: Demonstrates how to use the flutter_llama plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_llama:
    path: ../

  cupertino_icons: ^1.0.2
  network_file_cached: ^0.0.7
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  xdg_directories: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
